import type { PetTemplate } from './petCreationTypes'

export const petTemplateFilters = [
  '热门玩法',
  '对话口播',
  '剧情分镜',
  '图生视频',
  '表情反应',
  '唱跳动作',
  '商业科普',
  '背景场景',
]

function petAsset(fileName: string) {
  return new URL(`../../assets/pet-creation/${fileName}`, import.meta.url).href
}

export const petTemplates: PetTemplate[] = [
  {
    id: 'cat-dialogue',
    title: '小猫对话',
    description: '单宠或双宠台词互动，适合搞笑剧情、吐槽和反差梗。',
    coverUrl: petAsset('local-cat-dialogue.jpg'),
    category: '对话口播',
    videoType: 'dialogue',
    generationMode: 'dialogue_video',
    durationSeconds: 15,
    aspectRatio: '9:16',
    style: 'funny',
    tags: ['小猫', '对话', '字幕'],
    workflow: 'dialogue',
    promptPreset: '两只宠物在家里因为一件小事互相吐槽，台词短、反应快，结尾有反差笑点。',
    scriptPreset: '小猫先认真解释自己没有闯祸，第二只宠物马上补刀揭穿，小猫用撒娇收尾。',
    dialogueLines: [
      { id: 'tpl-cat-dialogue-1', speakerRoleId: 'main-cat', text: '我只是路过，真的没有偷玩。', emotion: '认真解释', speed: 'normal', voiceName: '软萌童声', lipSync: true },
      { id: 'tpl-cat-dialogue-2', speakerRoleId: 'second-dog', text: '那爪子上的证据怎么解释？', emotion: '吐槽', speed: 'normal', voiceName: '机智少年音', lipSync: true },
      { id: 'tpl-cat-dialogue-3', speakerRoleId: 'main-cat', text: '可能是证据自己跑过来的。', emotion: '撒娇', speed: 'normal', voiceName: '软萌童声', lipSync: true },
    ],
    subtitleEnabled: true,
    voiceEnabled: true,
    lipSyncEnabled: true,
    bgmEnabled: true,
    visualSettings: { cameraRhythm: 'short_drama', expressionIntensity: 78 },
  },
  {
    id: 'double-pet-dialogue',
    title: '双宠物对话',
    description: '两只宠物互相吐槽、争辩或合作完成小剧场，统一放入对话口播分类。',
    coverUrl: petAsset('local-double-dialogue.jpg'),
    category: '对话口播',
    videoType: 'dialogue',
    generationMode: 'dialogue_video',
    durationSeconds: 15,
    aspectRatio: '9:16',
    style: 'funny',
    tags: ['双宠物', '对话', '短剧'],
    workflow: 'dialogue',
    promptPreset: '两只宠物在同一个场景里互相争辩，一个装无辜，一个负责揭穿，节奏像短视频小剧场。',
    scriptPreset: '主宠提出一个离谱解释，第二只宠物指出破绽，最后两只宠物同框用可爱表情收尾。',
    dialogueLines: [
      { id: 'tpl-double-1', speakerRoleId: 'main-cat', text: '今天的沙发不是我弄乱的。', emotion: '认真解释', speed: 'normal', voiceName: '软萌童声', lipSync: true },
      { id: 'tpl-double-2', speakerRoleId: 'second-dog', text: '可是你刚刚还在沙发上开会。', emotion: '吐槽', speed: 'normal', voiceName: '机智少年音', lipSync: true },
      { id: 'tpl-double-3', speakerRoleId: 'main-cat', text: '那是临时会议，不能算。', emotion: '撒娇', speed: 'normal', voiceName: '软萌童声', lipSync: true },
    ],
    subtitleEnabled: true,
    voiceEnabled: true,
    lipSyncEnabled: true,
    bgmEnabled: true,
    visualSettings: { cameraRhythm: 'short_drama', expressionIntensity: 82 },
  },
  {
    id: 'pet-ai-smart-story',
    title: 'AI 智能创作',
    description: '像车辆 AI 智能创作一样，根据提示词自动生成宠物文案、对话和分镜。',
    coverUrl: petAsset('local-short-drama.jpg'),
    category: '剧情分镜',
    videoType: 'short_drama',
    generationMode: 'reference_video',
    durationSeconds: 15,
    aspectRatio: '9:16',
    style: 'cute',
    tags: ['AI文案', '分镜', '一键编排'],
    workflow: 'smart',
    promptPreset: '主宠在家里做了一件小坏事，被发现后露出无辜表情，用轻松可爱的剧情完成反转。',
    scriptPreset: '前 3 秒用反差开场，中段围绕宠物动作和表情递进，结尾用一句可转发的萌点收束。',
    subtitleEnabled: true,
    voiceEnabled: false,
    lipSyncEnabled: false,
    bgmEnabled: true,
    visualSettings: { cameraRhythm: 'balanced', expressionIntensity: 72 },
  },
  {
    id: 'viral-benchmark-storyboard',
    title: '爆款对标分镜',
    description: '参考短视频爆款结构，自动组织开场钩子、情绪递进和结尾包袱。',
    coverUrl: petAsset('local-short-drama.jpg'),
    category: '剧情分镜',
    videoType: 'short_drama',
    generationMode: 'reference_video',
    durationSeconds: 15,
    aspectRatio: '9:16',
    style: 'funny',
    tags: ['爆款对标', '分镜', '节奏'],
    workflow: 'storyboard',
    promptPreset: '参考爆款萌宠短视频结构：前三秒用反差钩子，中段突出宠物表情和动作，结尾用治愈或反转包袱收束。',
    scriptPreset: '钩子：宠物被发现的一瞬间。递进：用眼神、动作和字幕解释。收尾：一个无辜表情或反转台词。',
    shots: [
      { id: 'tpl-viral-shot-1', index: 1, durationSeconds: 3, frameDescription: '开场直接给出反差画面，宠物停住看向镜头', characterAction: '主宠瞬间定格，露出心虚又可爱的表情', cameraMove: '快速推近后稳定', subtitle: '糟糕，被发现了', voiceEmotion: '惊讶' },
      { id: 'tpl-viral-shot-2', index: 2, durationSeconds: 4, frameDescription: '中景展示宠物和现场证据，强化剧情冲突', characterAction: '主宠慢慢坐下，试图装作无事发生', cameraMove: '轻微跟拍', subtitle: '事情不是你想的那样', voiceEmotion: '认真解释' },
      { id: 'tpl-viral-shot-3', index: 3, durationSeconds: 4, frameDescription: '近景突出眼神、爪子或尾巴等萌点细节', characterAction: '主宠歪头、眨眼、尾巴轻轻晃动', cameraMove: '低机位慢推', subtitle: '我只是检查一下', voiceEmotion: '委屈' },
      { id: 'tpl-viral-shot-4', index: 4, durationSeconds: 4, frameDescription: '结尾回到宠物特写，用反转字幕收束', characterAction: '主宠靠近镜头，露出无辜表情', cameraMove: '固定近景', subtitle: '下次我会叫你一起', voiceEmotion: '撒娇' },
    ],
    subtitleEnabled: true,
    voiceEnabled: false,
    lipSyncEnabled: false,
    bgmEnabled: true,
    visualSettings: { cameraRhythm: 'short_drama', expressionIntensity: 86 },
  },
  {
    id: 'dog-reaction',
    title: '小狗机智反应',
    description: '突出表情、动作和反应节奏，适合 reaction 和搞笑短片。',
    coverUrl: petAsset('local-dog-reaction.jpg'),
    category: '表情反应',
    videoType: 'short_drama',
    generationMode: 'reference_video',
    durationSeconds: 10,
    aspectRatio: '9:16',
    style: 'cute',
    tags: ['小狗', '反应', '剧情'],
    workflow: 'storyboard',
    promptPreset: '小狗听到零食袋声音后突然抬头，努力保持镇定，最后忍不住露出期待表情。',
    subtitleEnabled: true,
    voiceEnabled: false,
    lipSyncEnabled: false,
    bgmEnabled: true,
    visualSettings: { cameraRhythm: 'fast', expressionIntensity: 80 },
  },
  {
    id: 'photo-to-video',
    title: '照片动起来',
    description: '上传单张宠物照片，生成轻剧情动态视频。',
    coverUrl: petAsset('local-photo-to-video.jpg'),
    category: '图生视频',
    videoType: 'image_to_video',
    generationMode: 'image_to_video',
    durationSeconds: 5,
    aspectRatio: '1:1',
    style: 'cute',
    tags: ['图生视频', '照片', '动态'],
    workflow: 'material',
    promptPreset: '让宠物照片自然动起来：轻轻眨眼、抬头看镜头，动作稳定，表情可爱。',
    subtitleEnabled: false,
    voiceEnabled: false,
    lipSyncEnabled: false,
    bgmEnabled: false,
    visualSettings: { cameraRhythm: 'slow', expressionIntensity: 55 },
  },
  {
    id: 'pet-sticker',
    title: '宠物表情包',
    description: '生成适合社群传播的宠物表情短片。',
    coverUrl: petAsset('local-pet-sticker.jpg'),
    category: '表情反应',
    videoType: 'sticker',
    generationMode: 'reference_video',
    durationSeconds: 5,
    aspectRatio: '1:1',
    style: 'funny',
    tags: ['表情包', '搞笑', '社群'],
    workflow: 'storyboard',
    promptPreset: '宠物做出夸张但自然的可爱表情，适合做聊天表情包，画面干净无文字水印。',
    subtitleEnabled: false,
    voiceEnabled: false,
    lipSyncEnabled: false,
    bgmEnabled: false,
    visualSettings: { cameraRhythm: 'fast', expressionIntensity: 92 },
  },
  {
    id: 'pet-dance-sing',
    title: '萌宠唱跳',
    description: '参考市面唱歌、跳舞、全身动效玩法，生成轻量动作短视频。',
    coverUrl: petAsset('local-pet-talking.jpg'),
    category: '唱跳动作',
    videoType: 'short_drama',
    generationMode: 'reference_video',
    durationSeconds: 10,
    aspectRatio: '9:16',
    style: 'funny',
    tags: ['唱跳', '动作', '短视频'],
    workflow: 'material',
    promptPreset: '宠物跟随轻快节奏做小幅度可爱动作，保持真实宠物身份和四肢结构，不做夸张变形。',
    subtitleEnabled: false,
    voiceEnabled: false,
    lipSyncEnabled: false,
    bgmEnabled: true,
    visualSettings: { cameraRhythm: 'fast', expressionIntensity: 75 },
  },
  {
    id: 'pet-talking',
    title: '宠物口播种草',
    description: '适合宠物用品介绍、门店活动和知识科普，文案可继续 AI 生成。',
    coverUrl: petAsset('local-pet-talking.jpg'),
    category: '商业科普',
    videoType: 'talking',
    generationMode: 'reference_video',
    durationSeconds: 30,
    aspectRatio: '9:16',
    style: 'realistic',
    tags: ['口播', '种草', '科普'],
    workflow: 'dialogue',
    promptPreset: '宠物以轻松口播方式介绍一个宠物用品或养宠小知识，语气真诚，不出现汽车销售内容。',
    scriptPreset: '开场提出一个养宠痛点，中段用宠物视角解释产品或知识点，结尾给出温和提醒。',
    subtitleEnabled: true,
    voiceEnabled: true,
    lipSyncEnabled: true,
    bgmEnabled: true,
    visualSettings: { cameraRhythm: 'balanced', expressionIntensity: 65 },
  },
  {
    id: 'pet-product-showcase',
    title: '宠物用品展示',
    description: '上传宠物和产品/道具图，生成宠物用品、零食、玩具或护理工具展示短片。',
    coverUrl: petAsset('local-pet-talking.jpg'),
    category: '商业科普',
    videoType: 'talking',
    generationMode: 'reference_video',
    durationSeconds: 15,
    aspectRatio: '9:16',
    style: 'realistic',
    tags: ['产品图', '用品展示', '种草'],
    workflow: 'material',
    promptPreset: '主宠自然靠近一个宠物用品或零食道具，画面真实干净，重点展示宠物和产品互动，不出现汽车销售内容。',
    scriptPreset: '开场展示主宠真实反应，中段让产品作为道具自然出现，结尾用一句轻松种草或养宠建议收束。',
    subtitleEnabled: true,
    voiceEnabled: false,
    lipSyncEnabled: false,
    bgmEnabled: true,
    visualSettings: {
      cameraRhythm: 'balanced',
      expressionIntensity: 66,
      productPrompt: '产品/道具自然出现在宠物旁边，不遮挡宠物脸部、毛色和主体动作。',
    },
    consistency: { keepAppearance: true, keepFurPattern: true },
  },
  {
    id: 'pet-monologue',
    title: '萌宠独白',
    description: '用第一视角讲述宠物日常和小剧场。',
    coverUrl: petAsset('local-pet-monologue.jpg'),
    category: '对话口播',
    videoType: 'monologue',
    generationMode: 'reference_video',
    durationSeconds: 15,
    aspectRatio: '9:16',
    style: 'healing',
    tags: ['独白', '治愈', '日常'],
    workflow: 'dialogue',
    promptPreset: '主宠用第一视角讲述今天的小心事，画面温柔治愈，动作轻微自然。',
    scriptPreset: '今天我又发现了一个很小但很开心的秘密，想慢慢讲给你听。',
    subtitleEnabled: true,
    voiceEnabled: true,
    lipSyncEnabled: false,
    bgmEnabled: true,
    visualSettings: { cameraRhythm: 'slow', expressionIntensity: 60 },
  },
  {
    id: 'background-scene-edit',
    title: '背景场景编辑',
    description: '为宠物视频补充或替换背景要求，结合场景参考图做稳定生成。',
    coverUrl: petAsset('local-scene-edit.jpg'),
    category: '背景场景',
    videoType: 'short_drama',
    generationMode: 'reference_video',
    durationSeconds: 10,
    aspectRatio: '9:16',
    style: 'realistic',
    tags: ['背景图', '场景', '参考图'],
    workflow: 'background',
    promptPreset: '主宠出现在干净温暖的室内场景中，背景自然统一，主体宠物清晰突出。',
    subtitleEnabled: false,
    voiceEnabled: false,
    lipSyncEnabled: false,
    bgmEnabled: false,
    visualSettings: {
      cameraRhythm: 'slow',
      expressionIntensity: 58,
      backgroundPrompt: '温暖客厅背景，浅景深，干净柔和，宠物主体清晰突出',
    },
    consistency: { keepScene: true },
  },
]

export function findPetTemplate(templateId?: string) {
  return petTemplates.find((template) => template.id === templateId)
}
